/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as A1RouteImport } from './routes/a1'
import { Route as A1plusRouteImport } from './routes/a1plus'
import { Route as AdministratorRouteImport } from './routes/administrator'
import { Route as AnomalyDetectionRouteImport } from './routes/anomaly-detection'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as BackupVerificationRouteImport } from './routes/backup-verification'
import { Route as BudgetRouteImport } from './routes/budget'
import { Route as CashFlowRouteImport } from './routes/cash-flow'
import { Route as DataExportRouteImport } from './routes/data-export'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DrawingsRouteImport } from './routes/drawings'
import { Route as GatePassRouteImport } from './routes/gate-pass'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as InventorySupervisorRouteImport } from './routes/inventory-supervisor'
import { Route as LabourRouteImport } from './routes/labour'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MedicalEquipmentRouteImport } from './routes/medical-equipment'
import { Route as NotificationSettingsRouteImport } from './routes/notification-settings'
import { Route as PartsOrdersRouteImport } from './routes/parts-orders'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as ProgressConfigRouteImport } from './routes/progress-config'
import { Route as ProgressDashboardRouteImport } from './routes/progress-dashboard'
import { Route as ProgressTrackingRouteImport } from './routes/progress-tracking'
import { Route as PunchListRouteImport } from './routes/punch-list'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as RegistersRouteImport } from './routes/registers'
import { Route as RetentionRouteImport } from './routes/retention'
import { Route as RoleAuditRouteImport } from './routes/role-audit'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as TdsGstRouteImport } from './routes/tds-gst'
import { Route as TraceabilityRouteImport } from './routes/traceability'
import { Route as UsersRouteImport } from './routes/users'
import { Route as VendorScorecardRouteImport } from './routes/vendor-scorecard'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as WorkOrdersRouteImport } from './routes/work-orders'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as LoginA1RouteImport } from './routes/login.a1'
import { Route as LoginA1plusRouteImport } from './routes/login.a1plus'
import { Route as LoginAdministratorRouteImport } from './routes/login.administrator'
import { Route as LoginSupervisorRouteImport } from './routes/login.supervisor'
import { Route as PortalA1RouteImport } from './routes/portal.a1'
import { Route as PortalA1plusRouteImport } from './routes/portal.a1plus'
import { Route as PortalAdministratorRouteImport } from './routes/portal.administrator'
import { Route as PortalSupervisorRouteImport } from './routes/portal.supervisor'
import { Route as PortalClientIndexRouteImport } from './routes/portal/client/index'
import { Route as PortalClientLoginRouteImport } from './routes/portal/client/login'
import { Route as PortalVendorIndexRouteImport } from './routes/portal/vendor/index'
import { Route as PortalVendorLoginRouteImport } from './routes/portal/vendor/login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const A1Route = A1RouteImport.update({
  id: '/a1',
  path: '/a1',
  getParentRoute: () => rootRouteImport,
} as any)
const A1plusRoute = A1plusRouteImport.update({
  id: '/a1plus',
  path: '/a1plus',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministratorRoute = AdministratorRouteImport.update({
  id: '/administrator',
  path: '/administrator',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomalyDetectionRoute = AnomalyDetectionRouteImport.update({
  id: '/anomaly-detection',
  path: '/anomaly-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupVerificationRoute = BackupVerificationRouteImport.update({
  id: '/backup-verification',
  path: '/backup-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const BudgetRoute = BudgetRouteImport.update({
  id: '/budget',
  path: '/budget',
  getParentRoute: () => rootRouteImport,
} as any)
const CashFlowRoute = CashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => rootRouteImport,
} as any)
const DataExportRoute = DataExportRouteImport.update({
  id: '/data-export',
  path: '/data-export',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DrawingsRoute = DrawingsRouteImport.update({
  id: '/drawings',
  path: '/drawings',
  getParentRoute: () => rootRouteImport,
} as any)
const GatePassRoute = GatePassRouteImport.update({
  id: '/gate-pass',
  path: '/gate-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const InventorySupervisorRoute = InventorySupervisorRouteImport.update({
  id: '/inventory-supervisor',
  path: '/inventory-supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const LabourRoute = LabourRouteImport.update({
  id: '/labour',
  path: '/labour',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicalEquipmentRoute = MedicalEquipmentRouteImport.update({
  id: '/medical-equipment',
  path: '/medical-equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationSettingsRoute = NotificationSettingsRouteImport.update({
  id: '/notification-settings',
  path: '/notification-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsOrdersRoute = PartsOrdersRouteImport.update({
  id: '/parts-orders',
  path: '/parts-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressConfigRoute = ProgressConfigRouteImport.update({
  id: '/progress-config',
  path: '/progress-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressDashboardRoute = ProgressDashboardRouteImport.update({
  id: '/progress-dashboard',
  path: '/progress-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressTrackingRoute = ProgressTrackingRouteImport.update({
  id: '/progress-tracking',
  path: '/progress-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const PunchListRoute = PunchListRouteImport.update({
  id: '/punch-list',
  path: '/punch-list',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistersRoute = RegistersRouteImport.update({
  id: '/registers',
  path: '/registers',
  getParentRoute: () => rootRouteImport,
} as any)
const RetentionRoute = RetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => rootRouteImport,
} as any)
const RoleAuditRoute = RoleAuditRouteImport.update({
  id: '/role-audit',
  path: '/role-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const TdsGstRoute = TdsGstRouteImport.update({
  id: '/tds-gst',
  path: '/tds-gst',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceabilityRoute = TraceabilityRouteImport.update({
  id: '/traceability',
  path: '/traceability',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorScorecardRoute = VendorScorecardRouteImport.update({
  id: '/vendor-scorecard',
  path: '/vendor-scorecard',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkOrdersRoute = WorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const LoginA1Route = LoginA1RouteImport.update({
  id: '/a1',
  path: '/a1',
  getParentRoute: () => LoginRoute,
} as any)
const LoginA1plusRoute = LoginA1plusRouteImport.update({
  id: '/a1plus',
  path: '/a1plus',
  getParentRoute: () => LoginRoute,
} as any)
const LoginAdministratorRoute = LoginAdministratorRouteImport.update({
  id: '/administrator',
  path: '/administrator',
  getParentRoute: () => LoginRoute,
} as any)
const LoginSupervisorRoute = LoginSupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => LoginRoute,
} as any)
const PortalA1Route = PortalA1RouteImport.update({
  id: '/a1',
  path: '/a1',
  getParentRoute: () => PortalRoute,
} as any)
const PortalA1plusRoute = PortalA1plusRouteImport.update({
  id: '/a1plus',
  path: '/a1plus',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdministratorRoute = PortalAdministratorRouteImport.update({
  id: '/administrator',
  path: '/administrator',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSupervisorRoute = PortalSupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => PortalRoute,
} as any)
const PortalClientIndexRoute = PortalClientIndexRouteImport.update({
  id: '/client/',
  path: '/client/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalClientLoginRoute = PortalClientLoginRouteImport.update({
  id: '/client/login',
  path: '/client/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalVendorIndexRoute = PortalVendorIndexRouteImport.update({
  id: '/vendor/',
  path: '/vendor/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalVendorLoginRoute = PortalVendorLoginRouteImport.update({
  id: '/vendor/login',
  path: '/vendor/login',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a1': typeof A1Route
  '/a1plus': typeof A1plusRoute
  '/administrator': typeof AdministratorRoute
  '/anomaly-detection': typeof AnomalyDetectionRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-log': typeof AuditLogRoute
  '/backup-verification': typeof BackupVerificationRoute
  '/budget': typeof BudgetRoute
  '/cash-flow': typeof CashFlowRoute
  '/data-export': typeof DataExportRoute
  '/documents': typeof DocumentsRoute
  '/drawings': typeof DrawingsRoute
  '/gate-pass': typeof GatePassRoute
  '/inventory': typeof InventoryRoute
  '/inventory-supervisor': typeof InventorySupervisorRoute
  '/labour': typeof LabourRoute
  '/login': typeof LoginRouteWithChildren
  '/medical-equipment': typeof MedicalEquipmentRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/parts-orders': typeof PartsOrdersRoute
  '/portal': typeof PortalRouteWithChildren
  '/procurement': typeof ProcurementRoute
  '/progress-config': typeof ProgressConfigRoute
  '/progress-dashboard': typeof ProgressDashboardRoute
  '/progress-tracking': typeof ProgressTrackingRoute
  '/punch-list': typeof PunchListRoute
  '/quality': typeof QualityRoute
  '/registers': typeof RegistersRoute
  '/retention': typeof RetentionRoute
  '/role-audit': typeof RoleAuditRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/supervisor': typeof SupervisorRoute
  '/tds-gst': typeof TdsGstRoute
  '/traceability': typeof TraceabilityRoute
  '/users': typeof UsersRoute
  '/vendor-scorecard': typeof VendorScorecardRoute
  '/vendors': typeof VendorsRoute
  '/work-orders': typeof WorkOrdersRoute
  '/login/a1': typeof LoginA1Route
  '/login/a1plus': typeof LoginA1plusRoute
  '/login/administrator': typeof LoginAdministratorRoute
  '/login/supervisor': typeof LoginSupervisorRoute
  '/portal/a1': typeof PortalA1Route
  '/portal/a1plus': typeof PortalA1plusRoute
  '/portal/administrator': typeof PortalAdministratorRoute
  '/portal/supervisor': typeof PortalSupervisorRoute
  '/login/': typeof LoginIndexRoute
  '/portal/client/login': typeof PortalClientLoginRoute
  '/portal/vendor/login': typeof PortalVendorLoginRoute
  '/portal/client/': typeof PortalClientIndexRoute
  '/portal/vendor/': typeof PortalVendorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a1': typeof A1Route
  '/a1plus': typeof A1plusRoute
  '/administrator': typeof AdministratorRoute
  '/anomaly-detection': typeof AnomalyDetectionRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-log': typeof AuditLogRoute
  '/backup-verification': typeof BackupVerificationRoute
  '/budget': typeof BudgetRoute
  '/cash-flow': typeof CashFlowRoute
  '/data-export': typeof DataExportRoute
  '/documents': typeof DocumentsRoute
  '/drawings': typeof DrawingsRoute
  '/gate-pass': typeof GatePassRoute
  '/inventory': typeof InventoryRoute
  '/inventory-supervisor': typeof InventorySupervisorRoute
  '/labour': typeof LabourRoute
  '/medical-equipment': typeof MedicalEquipmentRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/parts-orders': typeof PartsOrdersRoute
  '/portal': typeof PortalRouteWithChildren
  '/procurement': typeof ProcurementRoute
  '/progress-config': typeof ProgressConfigRoute
  '/progress-dashboard': typeof ProgressDashboardRoute
  '/progress-tracking': typeof ProgressTrackingRoute
  '/punch-list': typeof PunchListRoute
  '/quality': typeof QualityRoute
  '/registers': typeof RegistersRoute
  '/retention': typeof RetentionRoute
  '/role-audit': typeof RoleAuditRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/supervisor': typeof SupervisorRoute
  '/tds-gst': typeof TdsGstRoute
  '/traceability': typeof TraceabilityRoute
  '/users': typeof UsersRoute
  '/vendor-scorecard': typeof VendorScorecardRoute
  '/vendors': typeof VendorsRoute
  '/work-orders': typeof WorkOrdersRoute
  '/login/a1': typeof LoginA1Route
  '/login/a1plus': typeof LoginA1plusRoute
  '/login/administrator': typeof LoginAdministratorRoute
  '/login/supervisor': typeof LoginSupervisorRoute
  '/portal/a1': typeof PortalA1Route
  '/portal/a1plus': typeof PortalA1plusRoute
  '/portal/administrator': typeof PortalAdministratorRoute
  '/portal/supervisor': typeof PortalSupervisorRoute
  '/login': typeof LoginIndexRoute
  '/portal/client/login': typeof PortalClientLoginRoute
  '/portal/vendor/login': typeof PortalVendorLoginRoute
  '/portal/client': typeof PortalClientIndexRoute
  '/portal/vendor': typeof PortalVendorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a1': typeof A1Route
  '/a1plus': typeof A1plusRoute
  '/administrator': typeof AdministratorRoute
  '/anomaly-detection': typeof AnomalyDetectionRoute
  '/approvals': typeof ApprovalsRoute
  '/audit-log': typeof AuditLogRoute
  '/backup-verification': typeof BackupVerificationRoute
  '/budget': typeof BudgetRoute
  '/cash-flow': typeof CashFlowRoute
  '/data-export': typeof DataExportRoute
  '/documents': typeof DocumentsRoute
  '/drawings': typeof DrawingsRoute
  '/gate-pass': typeof GatePassRoute
  '/inventory': typeof InventoryRoute
  '/inventory-supervisor': typeof InventorySupervisorRoute
  '/labour': typeof LabourRoute
  '/login': typeof LoginRouteWithChildren
  '/medical-equipment': typeof MedicalEquipmentRoute
  '/notification-settings': typeof NotificationSettingsRoute
  '/parts-orders': typeof PartsOrdersRoute
  '/portal': typeof PortalRouteWithChildren
  '/procurement': typeof ProcurementRoute
  '/progress-config': typeof ProgressConfigRoute
  '/progress-dashboard': typeof ProgressDashboardRoute
  '/progress-tracking': typeof ProgressTrackingRoute
  '/punch-list': typeof PunchListRoute
  '/quality': typeof QualityRoute
  '/registers': typeof RegistersRoute
  '/retention': typeof RetentionRoute
  '/role-audit': typeof RoleAuditRoute
  '/safety': typeof SafetyRoute
  '/settings': typeof SettingsRoute
  '/supervisor': typeof SupervisorRoute
  '/tds-gst': typeof TdsGstRoute
  '/traceability': typeof TraceabilityRoute
  '/users': typeof UsersRoute
  '/vendor-scorecard': typeof VendorScorecardRoute
  '/vendors': typeof VendorsRoute
  '/work-orders': typeof WorkOrdersRoute
  '/login/a1': typeof LoginA1Route
  '/login/a1plus': typeof LoginA1plusRoute
  '/login/administrator': typeof LoginAdministratorRoute
  '/login/supervisor': typeof LoginSupervisorRoute
  '/portal/a1': typeof PortalA1Route
  '/portal/a1plus': typeof PortalA1plusRoute
  '/portal/administrator': typeof PortalAdministratorRoute
  '/portal/supervisor': typeof PortalSupervisorRoute
  '/login/': typeof LoginIndexRoute
  '/portal/client/login': typeof PortalClientLoginRoute
  '/portal/vendor/login': typeof PortalVendorLoginRoute
  '/portal/client/': typeof PortalClientIndexRoute
  '/portal/vendor/': typeof PortalVendorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a1'
    | '/a1plus'
    | '/administrator'
    | '/anomaly-detection'
    | '/approvals'
    | '/audit-log'
    | '/backup-verification'
    | '/budget'
    | '/cash-flow'
    | '/data-export'
    | '/documents'
    | '/drawings'
    | '/gate-pass'
    | '/inventory'
    | '/inventory-supervisor'
    | '/labour'
    | '/login'
    | '/medical-equipment'
    | '/notification-settings'
    | '/parts-orders'
    | '/portal'
    | '/procurement'
    | '/progress-config'
    | '/progress-dashboard'
    | '/progress-tracking'
    | '/punch-list'
    | '/quality'
    | '/registers'
    | '/retention'
    | '/role-audit'
    | '/safety'
    | '/settings'
    | '/supervisor'
    | '/tds-gst'
    | '/traceability'
    | '/users'
    | '/vendor-scorecard'
    | '/vendors'
    | '/work-orders'
    | '/login/a1'
    | '/login/a1plus'
    | '/login/administrator'
    | '/login/supervisor'
    | '/portal/a1'
    | '/portal/a1plus'
    | '/portal/administrator'
    | '/portal/supervisor'
    | '/login/'
    | '/portal/client/login'
    | '/portal/vendor/login'
    | '/portal/client/'
    | '/portal/vendor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a1'
    | '/a1plus'
    | '/administrator'
    | '/anomaly-detection'
    | '/approvals'
    | '/audit-log'
    | '/backup-verification'
    | '/budget'
    | '/cash-flow'
    | '/data-export'
    | '/documents'
    | '/drawings'
    | '/gate-pass'
    | '/inventory'
    | '/inventory-supervisor'
    | '/labour'
    | '/medical-equipment'
    | '/notification-settings'
    | '/parts-orders'
    | '/portal'
    | '/procurement'
    | '/progress-config'
    | '/progress-dashboard'
    | '/progress-tracking'
    | '/punch-list'
    | '/quality'
    | '/registers'
    | '/retention'
    | '/role-audit'
    | '/safety'
    | '/settings'
    | '/supervisor'
    | '/tds-gst'
    | '/traceability'
    | '/users'
    | '/vendor-scorecard'
    | '/vendors'
    | '/work-orders'
    | '/login/a1'
    | '/login/a1plus'
    | '/login/administrator'
    | '/login/supervisor'
    | '/portal/a1'
    | '/portal/a1plus'
    | '/portal/administrator'
    | '/portal/supervisor'
    | '/login'
    | '/portal/client/login'
    | '/portal/vendor/login'
    | '/portal/client'
    | '/portal/vendor'
  id:
    | '__root__'
    | '/'
    | '/a1'
    | '/a1plus'
    | '/administrator'
    | '/anomaly-detection'
    | '/approvals'
    | '/audit-log'
    | '/backup-verification'
    | '/budget'
    | '/cash-flow'
    | '/data-export'
    | '/documents'
    | '/drawings'
    | '/gate-pass'
    | '/inventory'
    | '/inventory-supervisor'
    | '/labour'
    | '/login'
    | '/medical-equipment'
    | '/notification-settings'
    | '/parts-orders'
    | '/portal'
    | '/procurement'
    | '/progress-config'
    | '/progress-dashboard'
    | '/progress-tracking'
    | '/punch-list'
    | '/quality'
    | '/registers'
    | '/retention'
    | '/role-audit'
    | '/safety'
    | '/settings'
    | '/supervisor'
    | '/tds-gst'
    | '/traceability'
    | '/users'
    | '/vendor-scorecard'
    | '/vendors'
    | '/work-orders'
    | '/login/a1'
    | '/login/a1plus'
    | '/login/administrator'
    | '/login/supervisor'
    | '/portal/a1'
    | '/portal/a1plus'
    | '/portal/administrator'
    | '/portal/supervisor'
    | '/login/'
    | '/portal/client/login'
    | '/portal/vendor/login'
    | '/portal/client/'
    | '/portal/vendor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  A1Route: typeof A1Route
  A1plusRoute: typeof A1plusRoute
  AdministratorRoute: typeof AdministratorRoute
  AnomalyDetectionRoute: typeof AnomalyDetectionRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditLogRoute: typeof AuditLogRoute
  BackupVerificationRoute: typeof BackupVerificationRoute
  BudgetRoute: typeof BudgetRoute
  CashFlowRoute: typeof CashFlowRoute
  DataExportRoute: typeof DataExportRoute
  DocumentsRoute: typeof DocumentsRoute
  DrawingsRoute: typeof DrawingsRoute
  GatePassRoute: typeof GatePassRoute
  InventoryRoute: typeof InventoryRoute
  InventorySupervisorRoute: typeof InventorySupervisorRoute
  LabourRoute: typeof LabourRoute
  LoginRoute: typeof LoginRouteWithChildren
  MedicalEquipmentRoute: typeof MedicalEquipmentRoute
  NotificationSettingsRoute: typeof NotificationSettingsRoute
  PartsOrdersRoute: typeof PartsOrdersRoute
  PortalRoute: typeof PortalRouteWithChildren
  ProcurementRoute: typeof ProcurementRoute
  ProgressConfigRoute: typeof ProgressConfigRoute
  ProgressDashboardRoute: typeof ProgressDashboardRoute
  ProgressTrackingRoute: typeof ProgressTrackingRoute
  PunchListRoute: typeof PunchListRoute
  QualityRoute: typeof QualityRoute
  RegistersRoute: typeof RegistersRoute
  RetentionRoute: typeof RetentionRoute
  RoleAuditRoute: typeof RoleAuditRoute
  SafetyRoute: typeof SafetyRoute
  SettingsRoute: typeof SettingsRoute
  SupervisorRoute: typeof SupervisorRoute
  TdsGstRoute: typeof TdsGstRoute
  TraceabilityRoute: typeof TraceabilityRoute
  UsersRoute: typeof UsersRoute
  VendorScorecardRoute: typeof VendorScorecardRoute
  VendorsRoute: typeof VendorsRoute
  WorkOrdersRoute: typeof WorkOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a1': {
      id: '/a1'
      path: '/a1'
      fullPath: '/a1'
      preLoaderRoute: typeof A1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a1plus': {
      id: '/a1plus'
      path: '/a1plus'
      fullPath: '/a1plus'
      preLoaderRoute: typeof A1plusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrator': {
      id: '/administrator'
      path: '/administrator'
      fullPath: '/administrator'
      preLoaderRoute: typeof AdministratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomaly-detection': {
      id: '/anomaly-detection'
      path: '/anomaly-detection'
      fullPath: '/anomaly-detection'
      preLoaderRoute: typeof AnomalyDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup-verification': {
      id: '/backup-verification'
      path: '/backup-verification'
      fullPath: '/backup-verification'
      preLoaderRoute: typeof BackupVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/budget': {
      id: '/budget'
      path: '/budget'
      fullPath: '/budget'
      preLoaderRoute: typeof BudgetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash-flow': {
      id: '/cash-flow'
      path: '/cash-flow'
      fullPath: '/cash-flow'
      preLoaderRoute: typeof CashFlowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-export': {
      id: '/data-export'
      path: '/data-export'
      fullPath: '/data-export'
      preLoaderRoute: typeof DataExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drawings': {
      id: '/drawings'
      path: '/drawings'
      fullPath: '/drawings'
      preLoaderRoute: typeof DrawingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate-pass': {
      id: '/gate-pass'
      path: '/gate-pass'
      fullPath: '/gate-pass'
      preLoaderRoute: typeof GatePassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory-supervisor': {
      id: '/inventory-supervisor'
      path: '/inventory-supervisor'
      fullPath: '/inventory-supervisor'
      preLoaderRoute: typeof InventorySupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labour': {
      id: '/labour'
      path: '/labour'
      fullPath: '/labour'
      preLoaderRoute: typeof LabourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medical-equipment': {
      id: '/medical-equipment'
      path: '/medical-equipment'
      fullPath: '/medical-equipment'
      preLoaderRoute: typeof MedicalEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notification-settings': {
      id: '/notification-settings'
      path: '/notification-settings'
      fullPath: '/notification-settings'
      preLoaderRoute: typeof NotificationSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts-orders': {
      id: '/parts-orders'
      path: '/parts-orders'
      fullPath: '/parts-orders'
      preLoaderRoute: typeof PartsOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress-config': {
      id: '/progress-config'
      path: '/progress-config'
      fullPath: '/progress-config'
      preLoaderRoute: typeof ProgressConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress-dashboard': {
      id: '/progress-dashboard'
      path: '/progress-dashboard'
      fullPath: '/progress-dashboard'
      preLoaderRoute: typeof ProgressDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress-tracking': {
      id: '/progress-tracking'
      path: '/progress-tracking'
      fullPath: '/progress-tracking'
      preLoaderRoute: typeof ProgressTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/punch-list': {
      id: '/punch-list'
      path: '/punch-list'
      fullPath: '/punch-list'
      preLoaderRoute: typeof PunchListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registers': {
      id: '/registers'
      path: '/registers'
      fullPath: '/registers'
      preLoaderRoute: typeof RegistersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/retention': {
      id: '/retention'
      path: '/retention'
      fullPath: '/retention'
      preLoaderRoute: typeof RetentionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/role-audit': {
      id: '/role-audit'
      path: '/role-audit'
      fullPath: '/role-audit'
      preLoaderRoute: typeof RoleAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tds-gst': {
      id: '/tds-gst'
      path: '/tds-gst'
      fullPath: '/tds-gst'
      preLoaderRoute: typeof TdsGstRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traceability': {
      id: '/traceability'
      path: '/traceability'
      fullPath: '/traceability'
      preLoaderRoute: typeof TraceabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendor-scorecard': {
      id: '/vendor-scorecard'
      path: '/vendor-scorecard'
      fullPath: '/vendor-scorecard'
      preLoaderRoute: typeof VendorScorecardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work-orders': {
      id: '/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof WorkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/a1': {
      id: '/login/a1'
      path: '/a1'
      fullPath: '/login/a1'
      preLoaderRoute: typeof LoginA1RouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/a1plus': {
      id: '/login/a1plus'
      path: '/a1plus'
      fullPath: '/login/a1plus'
      preLoaderRoute: typeof LoginA1plusRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/administrator': {
      id: '/login/administrator'
      path: '/administrator'
      fullPath: '/login/administrator'
      preLoaderRoute: typeof LoginAdministratorRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/supervisor': {
      id: '/login/supervisor'
      path: '/supervisor'
      fullPath: '/login/supervisor'
      preLoaderRoute: typeof LoginSupervisorRouteImport
      parentRoute: typeof LoginRoute
    }
    '/portal/a1': {
      id: '/portal/a1'
      path: '/a1'
      fullPath: '/portal/a1'
      preLoaderRoute: typeof PortalA1RouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/a1plus': {
      id: '/portal/a1plus'
      path: '/a1plus'
      fullPath: '/portal/a1plus'
      preLoaderRoute: typeof PortalA1plusRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/administrator': {
      id: '/portal/administrator'
      path: '/administrator'
      fullPath: '/portal/administrator'
      preLoaderRoute: typeof PortalAdministratorRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/supervisor': {
      id: '/portal/supervisor'
      path: '/supervisor'
      fullPath: '/portal/supervisor'
      preLoaderRoute: typeof PortalSupervisorRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/client/': {
      id: '/portal/client/'
      path: '/client'
      fullPath: '/portal/client/'
      preLoaderRoute: typeof PortalClientIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/client/login': {
      id: '/portal/client/login'
      path: '/client/login'
      fullPath: '/portal/client/login'
      preLoaderRoute: typeof PortalClientLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/vendor/': {
      id: '/portal/vendor/'
      path: '/vendor'
      fullPath: '/portal/vendor/'
      preLoaderRoute: typeof PortalVendorIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/vendor/login': {
      id: '/portal/vendor/login'
      path: '/vendor/login'
      fullPath: '/portal/vendor/login'
      preLoaderRoute: typeof PortalVendorLoginRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface LoginRouteChildren {
  LoginA1Route: typeof LoginA1Route
  LoginA1plusRoute: typeof LoginA1plusRoute
  LoginAdministratorRoute: typeof LoginAdministratorRoute
  LoginSupervisorRoute: typeof LoginSupervisorRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginA1Route: LoginA1Route,
  LoginA1plusRoute: LoginA1plusRoute,
  LoginAdministratorRoute: LoginAdministratorRoute,
  LoginSupervisorRoute: LoginSupervisorRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

interface PortalRouteChildren {
  PortalA1Route: typeof PortalA1Route
  PortalA1plusRoute: typeof PortalA1plusRoute
  PortalAdministratorRoute: typeof PortalAdministratorRoute
  PortalSupervisorRoute: typeof PortalSupervisorRoute
  PortalClientLoginRoute: typeof PortalClientLoginRoute
  PortalVendorLoginRoute: typeof PortalVendorLoginRoute
  PortalClientIndexRoute: typeof PortalClientIndexRoute
  PortalVendorIndexRoute: typeof PortalVendorIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalA1Route: PortalA1Route,
  PortalA1plusRoute: PortalA1plusRoute,
  PortalAdministratorRoute: PortalAdministratorRoute,
  PortalSupervisorRoute: PortalSupervisorRoute,
  PortalClientLoginRoute: PortalClientLoginRoute,
  PortalVendorLoginRoute: PortalVendorLoginRoute,
  PortalClientIndexRoute: PortalClientIndexRoute,
  PortalVendorIndexRoute: PortalVendorIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  A1Route: A1Route,
  A1plusRoute: A1plusRoute,
  AdministratorRoute: AdministratorRoute,
  AnomalyDetectionRoute: AnomalyDetectionRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditLogRoute: AuditLogRoute,
  BackupVerificationRoute: BackupVerificationRoute,
  BudgetRoute: BudgetRoute,
  CashFlowRoute: CashFlowRoute,
  DataExportRoute: DataExportRoute,
  DocumentsRoute: DocumentsRoute,
  DrawingsRoute: DrawingsRoute,
  GatePassRoute: GatePassRoute,
  InventoryRoute: InventoryRoute,
  InventorySupervisorRoute: InventorySupervisorRoute,
  LabourRoute: LabourRoute,
  LoginRoute: LoginRouteWithChildren,
  MedicalEquipmentRoute: MedicalEquipmentRoute,
  NotificationSettingsRoute: NotificationSettingsRoute,
  PartsOrdersRoute: PartsOrdersRoute,
  PortalRoute: PortalRouteWithChildren,
  ProcurementRoute: ProcurementRoute,
  ProgressConfigRoute: ProgressConfigRoute,
  ProgressDashboardRoute: ProgressDashboardRoute,
  ProgressTrackingRoute: ProgressTrackingRoute,
  PunchListRoute: PunchListRoute,
  QualityRoute: QualityRoute,
  RegistersRoute: RegistersRoute,
  RetentionRoute: RetentionRoute,
  RoleAuditRoute: RoleAuditRoute,
  SafetyRoute: SafetyRoute,
  SettingsRoute: SettingsRoute,
  SupervisorRoute: SupervisorRoute,
  TdsGstRoute: TdsGstRoute,
  TraceabilityRoute: TraceabilityRoute,
  UsersRoute: UsersRoute,
  VendorScorecardRoute: VendorScorecardRoute,
  VendorsRoute: VendorsRoute,
  WorkOrdersRoute: WorkOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
