/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as A1RouteImport } from './routes/a1'
import { Route as A1plusRouteImport } from './routes/a1plus'
import { Route as AdministratorRouteImport } from './routes/administrator'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as GatePassRouteImport } from './routes/gate-pass'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProcurementRouteImport } from './routes/procurement'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as RegistersRouteImport } from './routes/registers'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as TraceabilityRouteImport } from './routes/traceability'
import { Route as LoginIndexRouteImport } from './routes/login.index'
import { Route as LoginSupervisorRouteImport } from './routes/login.supervisor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const A1Route = A1RouteImport.update({
  id: '/a1',
  path: '/a1',
  getParentRoute: () => rootRouteImport,
} as any)
const A1plusRoute = A1plusRouteImport.update({
  id: '/a1plus',
  path: '/a1plus',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministratorRoute = AdministratorRouteImport.update({
  id: '/administrator',
  path: '/administrator',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const GatePassRoute = GatePassRouteImport.update({
  id: '/gate-pass',
  path: '/gate-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcurementRoute = ProcurementRouteImport.update({
  id: '/procurement',
  path: '/procurement',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistersRoute = RegistersRouteImport.update({
  id: '/registers',
  path: '/registers',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const TraceabilityRoute = TraceabilityRouteImport.update({
  id: '/traceability',
  path: '/traceability',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)
const LoginSupervisorRoute = LoginSupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => LoginRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a1': typeof A1Route
  '/a1plus': typeof A1plusRoute
  '/administrator': typeof AdministratorRoute
  '/approvals': typeof ApprovalsRoute
  '/gate-pass': typeof GatePassRoute
  '/login': typeof LoginRouteWithChildren
  '/procurement': typeof ProcurementRoute
  '/quality': typeof QualityRoute
  '/registers': typeof RegistersRoute
  '/supervisor': typeof SupervisorRoute
  '/traceability': typeof TraceabilityRoute
  '/login/supervisor': typeof LoginSupervisorRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a1': typeof A1Route
  '/a1plus': typeof A1plusRoute
  '/administrator': typeof AdministratorRoute
  '/approvals': typeof ApprovalsRoute
  '/gate-pass': typeof GatePassRoute
  '/procurement': typeof ProcurementRoute
  '/quality': typeof QualityRoute
  '/registers': typeof RegistersRoute
  '/supervisor': typeof SupervisorRoute
  '/traceability': typeof TraceabilityRoute
  '/login/supervisor': typeof LoginSupervisorRoute
  '/login': typeof LoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a1': typeof A1Route
  '/a1plus': typeof A1plusRoute
  '/administrator': typeof AdministratorRoute
  '/approvals': typeof ApprovalsRoute
  '/gate-pass': typeof GatePassRoute
  '/login': typeof LoginRouteWithChildren
  '/procurement': typeof ProcurementRoute
  '/quality': typeof QualityRoute
  '/registers': typeof RegistersRoute
  '/supervisor': typeof SupervisorRoute
  '/traceability': typeof TraceabilityRoute
  '/login/supervisor': typeof LoginSupervisorRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a1'
    | '/a1plus'
    | '/administrator'
    | '/approvals'
    | '/gate-pass'
    | '/login'
    | '/procurement'
    | '/quality'
    | '/registers'
    | '/supervisor'
    | '/traceability'
    | '/login/supervisor'
    | '/login/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a1'
    | '/a1plus'
    | '/administrator'
    | '/approvals'
    | '/gate-pass'
    | '/procurement'
    | '/quality'
    | '/registers'
    | '/supervisor'
    | '/traceability'
    | '/login/supervisor'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/a1'
    | '/a1plus'
    | '/administrator'
    | '/approvals'
    | '/gate-pass'
    | '/login'
    | '/procurement'
    | '/quality'
    | '/registers'
    | '/supervisor'
    | '/traceability'
    | '/login/supervisor'
    | '/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  A1Route: typeof A1Route
  A1plusRoute: typeof A1plusRoute
  AdministratorRoute: typeof AdministratorRoute
  ApprovalsRoute: typeof ApprovalsRoute
  GatePassRoute: typeof GatePassRoute
  LoginRoute: typeof LoginRouteWithChildren
  ProcurementRoute: typeof ProcurementRoute
  QualityRoute: typeof QualityRoute
  RegistersRoute: typeof RegistersRoute
  SupervisorRoute: typeof SupervisorRoute
  TraceabilityRoute: typeof TraceabilityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a1': {
      id: '/a1'
      path: '/a1'
      fullPath: '/a1'
      preLoaderRoute: typeof A1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a1plus': {
      id: '/a1plus'
      path: '/a1plus'
      fullPath: '/a1plus'
      preLoaderRoute: typeof A1plusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrator': {
      id: '/administrator'
      path: '/administrator'
      fullPath: '/administrator'
      preLoaderRoute: typeof AdministratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gate-pass': {
      id: '/gate-pass'
      path: '/gate-pass'
      fullPath: '/gate-pass'
      preLoaderRoute: typeof GatePassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/procurement': {
      id: '/procurement'
      path: '/procurement'
      fullPath: '/procurement'
      preLoaderRoute: typeof ProcurementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registers': {
      id: '/registers'
      path: '/registers'
      fullPath: '/registers'
      preLoaderRoute: typeof RegistersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/traceability': {
      id: '/traceability'
      path: '/traceability'
      fullPath: '/traceability'
      preLoaderRoute: typeof TraceabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof LoginRoute
    }
    '/login/supervisor': {
      id: '/login/supervisor'
      path: '/supervisor'
      fullPath: '/login/supervisor'
      preLoaderRoute: typeof LoginSupervisorRouteImport
      parentRoute: typeof LoginRoute
    }
  }
}

interface LoginRouteChildren {
  LoginSupervisorRoute: typeof LoginSupervisorRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginSupervisorRoute: LoginSupervisorRoute,
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  A1Route: A1Route,
  A1plusRoute: A1plusRoute,
  AdministratorRoute: AdministratorRoute,
  ApprovalsRoute: ApprovalsRoute,
  GatePassRoute: GatePassRoute,
  LoginRoute: LoginRouteWithChildren,
  ProcurementRoute: ProcurementRoute,
  QualityRoute: QualityRoute,
  RegistersRoute: RegistersRoute,
  SupervisorRoute: SupervisorRoute,
  TraceabilityRoute: TraceabilityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
